name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Invoke Test
      run: yarn test

    - name: Test website Build
      run: |
        cd website
        yarn build
        cd ..

    - name: Test example Build
      run: |
        cd examples/extract-css
        yarn build
        cd ../..

